version: "3"
services:
    nginx:
        # image: nginx:stable-alpine
        build: ./nginx/
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    game_app:
        build: ./app/
        #image: cybercitizen01/the-ludo-game
        environment:
            - PORT=3000
        # depends_on:
        #     - nginx
